telegram:
  bot:
#    не вписывайте данные, так как можете отправить в публичный репозиторий
#    используйте переменные среды для установки значений
    username: {name}
    token: {token}
    notify:
      delay:
        value: 10
        unit: MINUTES

binance:
  api:
    getPrice: https://api.binance.com/api/v3/avgPrice?symbol=BTCUSDT

spring:
  datasource:
    driver:
      name: org.postgresql.Driver
    url: jdbc:postgresql://localhost:5432/db
    username: root
    password: root
    postgres_db: db
  jpa:
    properties:
      show-sql: true